version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - projeto-api-integrado_mongo_data:/data/db
    networks:
      - rede-projeto

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Vinilala1@
      MYSQL_DATABASE: usuarios_db
    ports:
      - "3307:3306"
    volumes:
      - projeto-api-integrado_mysql_data:/var/lib/mysql
    networks:
      - rede-projeto

  api-mongodb:
    build: ./usuario-api-mongodb
    container_name: api-mongodb
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    networks:
      - rede-projeto

  api-mysql:
    build: ./usuario-api-mysql
    container_name: api-mysql
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    networks:
      - rede-projeto

  frontend:
    build: ./meu-front-react
    container_name: frontend
    depends_on:
      - api-mysql
      - api-mongodb
    ports:
      - "5173:80"
    networks:
      - rede-projeto

networks:
  rede-projeto:
    driver: bridge

volumes:
  projeto-api-integrado_mysql_data:
  projeto-api-integrado_mongo_data:
